-keep class com.lmg.vk.engine.automix.nativecore.NativeTrackEffects { *; }
-keep class com.lmg.vk.engine.automix.nativecore.NativeTimePitch { *; }
-keep class com.lmg.vk.engine.automix.nativecore.NativeProcessedTrack { *; }
-keep class com.lmg.vk.engine.automix.nativecore.NativeObservationBridge { *; }
