#pragma once
#include "lmg/automix/planner_source_bindings.h"
#include "lmg/automix/planner_selection_binding.h"
#include "lmg/automix/styles.h"

namespace lmg::automix {
// Raw decoded catalog -> internal candidate descriptors. 27224d1f0 reads CodingKey
// 'duration' (tag2) into maximumBarCount:Int? at +0x18. No beats/seconds conversion.
// Host restrictions: <=14 records, unique nonnegative IDs and nonnegative counts.
// Absence remains absent; a present zero is NOT the source's absent->4 default.
std::vector<PlannerCandidateStyle> bindPlannerCatalogFields(
    const std::vector<TransitionStyle>& decodedCatalog);

struct PlannerMusicKitProviderBounds {
  double minimumOutgoingStart, minimumOutgoingEnd, maximumIncomingEnd;
};
// Reference = MusicKitAnalysis.duration in seconds, NOT Song.duration. The latter
// is a separate playback/confidence input in 27222a140 and the provider constructor.
// Getters 2722246f8/708/718 read the three constructor fields in this order.
PlannerMusicKitProviderBounds plannerMusicKitProviderBounds(double referenceDurationSeconds);

enum class PlannerSourceKnowledge : std::uint8_t { unknown, absent, present };
struct PlannerMusicKitSourceContext {
  PlannerOutgoingCriteria outgoingCriteria = PlannerOutgoingLateInSong{};
  PlannerIncomingCriteria incomingCriteria = PlannerCriteriaInSong{};
  // These are facts supplied by the recording/provider integration, not inferred
  // from URL extensions or a missing field in the reduced CloudSongAnalysis DTO.
  PlannerSourceKnowledge outgoingSpatial = PlannerSourceKnowledge::unknown;
  PlannerSourceKnowledge incomingSpatial = PlannerSourceKnowledge::unknown;
  PlannerSourceKnowledge outgoingPreviousState = PlannerSourceKnowledge::unknown;
  PlannerSourceKnowledge incomingPreviousState = PlannerSourceKnowledge::unknown;
  PlannerBeatMatchedEligibility upperEligibility = PlannerBeatMatchedEligibility::unresolved;
  PlannerAlgorithm maximumComplexity = PlannerAlgorithm::beatMatched;
};
// The first native supported subset is nonspatial MusicKit with confirmed absent
// previous playback state and EXACTLY matching known reference/playback durations.
// Equal-duration restriction is an LMG integration gate, not Apple's <2s confidence
// rule. It avoids silently mixing two coordinate systems in the existing preparation.
// No claim that a provider permission, supportsSmartTransitions or BPM alone resolves
// genre/support/spatial eligibility. The upper gate must be independently established.
enum class PlannerSourceContextStatus : std::uint8_t {
  resolved = 0, eligibilityUnresolved = 1, ineligible = 2,
  spatialUnsupported = 3, previousStateUnsupported = 4,
  referenceDurationMissing = 5, playbackDurationMissing = 6,
  durationMappingRequired = 7, invalidInput = 8,
  catalogRejected = 9, resourceLimit = 10, sourceFactsUnknown = 11,
  criteriaRejected = 12
};
struct PlannerSourceContextRequest {
  std::int64_t generation = 0, revision = 0;
  std::optional<std::int64_t> outgoingDurationMs, incomingDurationMs;
  std::uint64_t workBudget = kPlannerProducerWorkBudget;
  PlannerMusicKitSourceContext context;
};
struct PlannerSourceScopeResolution {
  PlannerSourceContextStatus status = PlannerSourceContextStatus::sourceFactsUnknown;
  // Original scalar binding request, generated by native source rules. Never a
  // pointer, PCM capability or user-supplied list of seed/tonality predicates.
  std::vector<std::int64_t> resolvedRequest;
};
PlannerSourceScopeResolution resolvePlannerSourceScope(
    const PlannerSourceContextRequest&, const CloudSongAnalysis& outgoing,
    const CloudSongAnalysis& incoming, const std::vector<TransitionStyle>& decodedCatalog);

inline constexpr std::int64_t kPlannerSourceRequestMagic = 0x4c4d47534d31;
inline constexpr std::int64_t kPlannerSourceResponseMagic = 0x4c4d47534e31;
inline constexpr std::size_t kPlannerSourceRequestWords = 24;
inline constexpr std::size_t kPlannerSourceResponseHeader = 12;
inline constexpr std::size_t kPlannerSourceMaxResponse = 140;
PlannerSourceContextRequest decodePlannerSourceContext(const std::vector<std::int64_t>&);
PlannerSourceContextStatus plannerSourceContextPreflight(const PlannerSourceContextRequest&);
// Stateless native composition. Envelope contains native-resolved scope + the
// unchanged V2 candidate report only when resolution succeeds. Rejections contain
// no descriptors, geometry, counters or provisional candidate. All are observation.
std::vector<std::int64_t> observePlannerSourceContext(
    const std::vector<std::int64_t>&, const CloudSongAnalysis&, const CloudSongAnalysis&,
    const std::vector<TransitionStyle>&);
std::vector<std::int64_t> observePlannerSourceContextJson(
    const std::vector<std::int64_t>&, std::string_view outgoing, std::string_view outgoingId,
    std::string_view incoming, std::string_view incomingId, std::string_view catalogJson);
} // namespace lmg::automix
