package com.lmg.vk.engine.automix.render

import org.junit.Test

/** Each scenario is a separate mandatory XML testcase; not a fake native/JNI count. */
class RenderBoundaryTest {
    @Test fun noPlan() = RenderBoundaryScenarios.run("noPlan")
    @Test fun outgoingOnly() = RenderBoundaryScenarios.run("outgoingOnly")
    @Test fun incomingOnly() = RenderBoundaryScenarios.run("incomingOnly")
    @Test fun bothNotExecutable() = RenderBoundaryScenarios.run("bothNotExecutable")
    @Test fun reservation() = RenderBoundaryScenarios.run("reservation")
    @Test fun rendererOrderNotRole() = RenderBoundaryScenarios.run("rendererOrderNotRole")
    @Test fun duplicateMediaIdsAreDistinct() = RenderBoundaryScenarios.run("duplicateMediaIdsAreDistinct")
    @Test fun wrongUriDoesNotBind() = RenderBoundaryScenarios.run("wrongUriDoesNotBind")
    @Test fun wrongRevisionDoesNotBind() = RenderBoundaryScenarios.run("wrongRevisionDoesNotBind")
    @Test fun wrongCacheKeyDoesNotBind() = RenderBoundaryScenarios.run("wrongCacheKeyDoesNotBind")
    @Test fun sameWindowRejected() = RenderBoundaryScenarios.run("sameWindowRejected")
    @Test fun duplicateRenderersRejected() = RenderBoundaryScenarios.run("duplicateRenderersRejected")
    @Test fun formatMismatch() = RenderBoundaryScenarios.run("formatMismatch")
    @Test fun nonPcmRejected() = RenderBoundaryScenarios.run("nonPcmRejected")
    @Test fun channelMapRejected() = RenderBoundaryScenarios.run("channelMapRejected")
    @Test fun encoderDelayRejected() = RenderBoundaryScenarios.run("encoderDelayRejected")
    @Test fun encoderPaddingRejected() = RenderBoundaryScenarios.run("encoderPaddingRejected")
    @Test fun multichannelRejected() = RenderBoundaryScenarios.run("multichannelRejected")
    @Test fun unsupportedSampleRate() = RenderBoundaryScenarios.run("unsupportedSampleRate")
    @Test fun tunnelingRejected() = RenderBoundaryScenarios.run("tunnelingRejected")
    @Test fun positionPastCue() = RenderBoundaryScenarios.run("positionPastCue")
    @Test fun equalPositionCue() = RenderBoundaryScenarios.run("equalPositionCue")
    @Test fun offsetConversion() = RenderBoundaryScenarios.run("offsetConversion")
    @Test fun windowPeriodOffset() = RenderBoundaryScenarios.run("windowPeriodOffset")
    @Test fun overflowRejected() = RenderBoundaryScenarios.run("overflowRejected")
    @Test fun partialCountsAcceptedOnly() = RenderBoundaryScenarios.run("partialCountsAcceptedOnly")
    @Test fun zeroAcceptanceDoesNotOwn() = RenderBoundaryScenarios.run("zeroAcceptanceDoesNotOwn")
    @Test fun bytesUntouched() = RenderBoundaryScenarios.run("bytesUntouched")
    @Test fun limitUnchanged() = RenderBoundaryScenarios.run("limitUnchanged")
    @Test fun sameException() = RenderBoundaryScenarios.run("sameException")
    @Test fun retryDifferentBufferRejected() = RenderBoundaryScenarios.run("retryDifferentBufferRejected")
    @Test fun retryPtsRejected() = RenderBoundaryScenarios.run("retryPtsRejected")
    @Test fun retryLimitRejected() = RenderBoundaryScenarios.run("retryLimitRejected")
    @Test fun retryPositionRejected() = RenderBoundaryScenarios.run("retryPositionRejected")
    @Test fun partialFrameRejected() = RenderBoundaryScenarios.run("partialFrameRejected")
    @Test fun falseFullRejected() = RenderBoundaryScenarios.run("falseFullRejected")
    @Test fun truePartialRejected() = RenderBoundaryScenarios.run("truePartialRejected")
    @Test fun zeroFrameNoAdvance() = RenderBoundaryScenarios.run("zeroFrameNoAdvance")
    @Test fun newBufferContinuity() = RenderBoundaryScenarios.run("newBufferContinuity")
    @Test fun newBufferJumpRejected() = RenderBoundaryScenarios.run("newBufferJumpRejected")
    @Test fun ptsUncertaintyIsConservative() = RenderBoundaryScenarios.run("ptsUncertaintyIsConservative")
    @Test fun unknownContext() = RenderBoundaryScenarios.run("unknownContext")
    @Test fun encodedUnitsRejected() = RenderBoundaryScenarios.run("encodedUnitsRejected")
    @Test fun newGenerationRevokes() = RenderBoundaryScenarios.run("newGenerationRevokes")
    @Test fun newRevisionRevokes() = RenderBoundaryScenarios.run("newRevisionRevokes")
    @Test fun stalePublicationIgnored() = RenderBoundaryScenarios.run("stalePublicationIgnored")
    @Test fun staleInvalidationIgnored() = RenderBoundaryScenarios.run("staleInvalidationIgnored")
    @Test fun invalidateSyncBarrier() = RenderBoundaryScenarios.run("invalidateSyncBarrier")
    @Test fun lateAfterCannotOverwrite() = RenderBoundaryScenarios.run("lateAfterCannotOverwrite")
    @Test fun newEpochStillKnowsQueuedPcm() = RenderBoundaryScenarios.run("newEpochStillKnowsQueuedPcm")
    @Test fun streamReplacementRevokes() = RenderBoundaryScenarios.run("streamReplacementRevokes")
    @Test fun flushRevokes() = RenderBoundaryScenarios.run("flushRevokes")
    @Test fun routeChangeRevokes() = RenderBoundaryScenarios.run("routeChangeRevokes")
    @Test fun speedChangeRevokes() = RenderBoundaryScenarios.run("speedChangeRevokes")
    @Test fun secondThreadFailsClosed() = RenderBoundaryScenarios.run("secondThreadFailsClosed")
    @Test fun closePermanent() = RenderBoundaryScenarios.run("closePermanent")
    @Test fun invalidPlanRejected() = RenderBoundaryScenarios.run("invalidPlanRejected")
    @Test fun redactedKeys() = RenderBoundaryScenarios.run("redactedKeys")
    @Test fun format16bitAccepted() = RenderBoundaryScenarios.run("format16bitAccepted")
    @Test fun oldIdentityNotInputIdentity() = RenderBoundaryScenarios.run("oldIdentityNotInputIdentity")
    @Test fun latePhysicalAcceptanceCarriedForward() = RenderBoundaryScenarios.run("latePhysicalAcceptanceCarriedForward")
    @Test fun diagnosticFailureCannotReplaceDelegateSuccess() = RenderBoundaryScenarios.run("diagnosticFailureCannotReplaceDelegateSuccess")
}
