package com.lmg.vk.engine

import android.media.AudioDeviceInfo
import android.media.AudioRouting
import android.os.Handler
import android.os.Looper
import androidx.media3.common.C
import androidx.media3.common.util.Clock
import androidx.media3.common.util.UnstableApi
import androidx.media3.common.util.Util
import androidx.media3.exoplayer.audio.AudioOutput
import androidx.media3.exoplayer.audio.AudioOutputProvider
import androidx.media3.exoplayer.audio.AudioTrackAudioOutput
import androidx.media3.exoplayer.analytics.PlayerId
import java.nio.ByteBuffer

/** Playback-thread owner of one reusable PCM output per sink. Each checkout gets a new lease:
 * retiring a lease resets PCM/position state without destroying the underlying AudioTrack.
 * No silent carrier, extra output, background writer, or shared audio-session ID is created.
 */
@UnstableApi
internal class RetainingAudioOutputProvider(
    private val delegate: AudioOutputProvider,
    private val enabled: Boolean,
    private val onCheckout: (AudioOutput) -> Unit = {},
    private val trace: (String) -> Unit = {},
) : AudioOutputProvider by delegate {
    // Java default methods are not generated by Kotlin interface delegation.
    override fun setClock(clock: Clock) = delegate.setClock(clock)
    override fun hasPendingReleases(): Boolean = delegate.hasPendingReleases()

    private var parked: Entry? = null
    private val active = mutableSetOf<Lease>()
    private var serial = 0
    private var closed = false
    private var listening = false
    private var preferredDeviceId: Int? = null
    private val capabilities = AudioOutputProvider.Listener { invalidate("capabilities-changed") }

    private inner class Entry(val output: AudioOutput, config: AudioOutputProvider.OutputConfig) {
        val id = ++serial
        val config = config.buildUpon().setAudioSessionId(output.audioSessionId).build()
        var reusable = enabled && Util.isEncodingLinearPcm(config.encoding) &&
            !config.isOffload && !config.isTunneling
        var destroyed = false
        var preferredDeviceId = this@RetainingAudioOutputProvider.preferredDeviceId
        var routedDeviceId: Int? = null
        var routingListener: AudioRouting.OnRoutingChangedListener? = null
        val track get() = (output as? AudioTrackAudioOutput)?.audioTrack

        fun observeRoute() {
            val track = track ?: return
            routedDeviceId = track.routedDevice?.id
            val listener = AudioRouting.OnRoutingChangedListener { routing ->
                // A paused track can report no routed device. Only a concrete device change
                // invalidates reuse; configuration/capability changes are checked separately.
                val next = routing.routedDevice?.id
                if (!destroyed && next != null) {
                    val previous = routedDeviceId
                    routedDeviceId = next
                    if (previous != null && previous != next) {
                        reusable = false
                        event("ROUTE_CHANGED", this)
                        if (parked === this) { parked = null; destroy("route-changed") }
                    }
                }
            }
            routingListener = listener
            track.addOnRoutingChangedListener(listener, Handler(checkNotNull(Looper.myLooper())))
        }

        fun matches(request: AudioOutputProvider.OutputConfig): Boolean {
            val normalized = if (request.audioSessionId == C.AUDIO_SESSION_ID_UNSET)
                request.buildUpon().setAudioSessionId(config.audioSessionId).build() else request
            return reusable && !destroyed && config == normalized
        }

        fun destroy(reason: String) {
            if (destroyed) return
            destroyed = true
            routingListener?.let { track?.removeOnRoutingChangedListener(it) }
            routingListener = null
            event("RELEASE reason=$reason", this)
            output.release()
        }
    }

    override fun getOutputConfig(format: AudioOutputProvider.FormatConfig): AudioOutputProvider.OutputConfig {
        val deviceId = format.preferredDevice?.id
        if (deviceId != preferredDeviceId) {
            preferredDeviceId = deviceId
            invalidate("preferred-device-changed")
        }
        val config = delegate.getOutputConfig(format)
        // Evict during configuration, so DefaultAudioSink can wait for pending native releases
        // before attempting initialization. getAudioOutput still checks again as a final guard.
        parked?.takeUnless { it.matches(config) }?.let {
            parked = null
            it.destroy("incompatible-configuration")
        }
        return config
    }

    override fun getAudioOutput(config: AudioOutputProvider.OutputConfig): AudioOutput {
        check(!closed) { "Audio output provider already released" }
        if (!listening) { delegate.addListener(capabilities); listening = true }
        val previous = parked
        parked = null
        val entry = if (previous != null && previous.matches(config)) {
            event("REUSE", previous)
            previous
        } else {
            previous?.destroy("incompatible-configuration")
            Entry(delegate.getAudioOutput(config), config).also {
                it.observeRoute()
                event("CREATE", it)
            }
        }
        return Lease(entry).also { active.add(it); onCheckout(entry.output) }
    }

    private fun event(action: String, entry: Entry) {
        trace("$action output=${entry.id} session=${entry.config.audioSessionId} " +
            "rate=${entry.config.sampleRate} channels=${entry.config.channelMask}")
    }

    private fun invalidate(reason: String) {
        active.forEach { it.entry.reusable = false }
        val old = parked
        parked = null
        old?.destroy(reason)
    }

    private inner class Lease(val entry: Entry) : AudioOutput by entry.output {
        override fun setPlayerId(playerId: PlayerId) = entry.output.setPlayerId(playerId)
        override fun canReuseAudioOutput(
            currentConfig: AudioOutputProvider.OutputConfig,
            newFormat: AudioOutputProvider.FormatConfig,
            newConfig: AudioOutputProvider.OutputConfig,
        ): Boolean = entry.output.canReuseAudioOutput(currentConfig, newFormat, newConfig)

        private val listeners = mutableSetOf<AudioOutput.Listener>()
        private var returned = false

        override fun addListener(listener: AudioOutput.Listener) {
            check(!returned)
            if (listeners.add(listener)) entry.output.addListener(listener)
        }
        override fun removeListener(listener: AudioOutput.Listener) {
            listeners.remove(listener)
            entry.output.removeListener(listener)
        }

        override fun write(buffer: ByteBuffer, units: Int, presentationTimeUs: Long): Boolean {
            check(!returned)
            try { return entry.output.write(buffer, units, presentationTimeUs) }
            catch (error: Exception) { entry.reusable = false; throw error }
        }

        override fun getPositionUs(): Long {
            try { return entry.output.positionUs }
            catch (error: RuntimeException) { entry.reusable = false; throw error }
        }

        override fun isStalled(): Boolean = entry.output.isStalled.also {
            if (it) entry.reusable = false
        }

        override fun setPreferredDevice(device: AudioDeviceInfo?) {
            // Explicit routing changes must not put the old configuration back in the pool.
            if (entry.preferredDeviceId != device?.id) entry.reusable = false
            entry.preferredDeviceId = device?.id
            entry.output.setPreferredDevice(device)
        }

        override fun stop() {
            if (entry.reusable) {
                // PCM continues draining normally. DefaultAudioSink checks actual position
                // against written frames before reporting ended. Parking then pauses/flushes.
                event("DRAIN", entry)
            } else entry.output.stop()
        }

        override fun release() {
            if (returned) return
            returned = true
            active.remove(this)
            listeners.forEach { entry.output.removeListener(it) }
            try {
                if (!closed && entry.reusable) {
                    try {
                        // Do not pause the AudioTrack: on MagicOS / EMUI calling pause()
                        // triggers AudioPolicy stopOutput and causes IAware/PowerGenie to
                        // freeze the process via cgroup.freeze after ~35 seconds.
                        // Keep the underlying track in PLAYSTATE_PLAYING.
                        parked?.destroy("replaced-idle-output")
                        parked = entry
                        event("PARK", entry)
                    } catch (error: RuntimeException) {
                        entry.reusable = false
                        event("PARK_FAILED error=${error.javaClass.simpleName}", entry)
                        entry.destroy("reset-failed")
                    }
                } else entry.destroy(if (closed) "provider-release" else "not-reusable")
            } finally {
                // This lease has ended; detach callbacks so later checkouts cannot notify it.
                // Physical AudioTrack destruction is recorded separately by RELEASE above.
                listeners.forEach { it.onReleased() }
                listeners.clear()
            }
        }
    }

    override fun release() {
        if (closed) return
        closed = true
        var failure: RuntimeException? = null
        fun cleanup(action: () -> Unit) {
            try { action() } catch (error: RuntimeException) {
                if (failure == null) failure = error else failure!!.addSuppressed(error)
            }
        }
        active.toList().forEach { lease -> cleanup { lease.release() } }
        val old = parked
        parked = null
        cleanup { old?.destroy("provider-release") }
        cleanup { if (listening) delegate.removeListener(capabilities) }
        cleanup { delegate.release() }
        failure?.let { throw it }
    }
}
